pipeline:
  install:
    image: monstrs/node-yarn:7.8
    commands:
      - yarn install

  lint:
    image: monstrs/node-yarn:7.8
    commands:
      - yarn run lint

  build:
    image: monstrs/node-yarn:7.8
    commands:
      - yarn run build

  deps:
    image: monstrs/node-yarn:7.8
    commands:
      - rm -r node_modules
      - yarn install --production

  ecr:
    image: plugins/ecr
    privileged: true
    repo: 592851895141.dkr.ecr.eu-central-1.amazonaws.com/landing
    region: eu-central-1
    tag:
      - v0.1.0-${DRONE_BUILD_NUMBER}
      - latest
