version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8500:80"

  install:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./.netrc:/root/.netrc
    entrypoint: npm install

  npm:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm

  dev:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run dev
    ports:
      - "3030:3030"

  build:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run build

  server:
    build: ./
    ports:
      - "3000:3000"
