version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8500:80"

  install:
    image: monstrs/node-yarn:7.8
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./.netrc:/root/.netrc
    entrypoint: yarn install

  install-prod:
    image: monstrs/node-yarn:7.8
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./.netrc:/root/.netrc
    entrypoint: yarn install --production

  yarn:
    image: monstrs/node-yarn:7.8
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./.netrc:/root/.netrc
    entrypoint: yarn

  dev:
    image: monstrs/node-yarn:7.8
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn run dev
    ports:
      - "80:3030"

  build:
    image: monstrs/node-yarn:7.8
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn run build

  landing:
    build: ./
    ports:
      - "3000:3000"

  proxy-dev:
    image: nginx:1.11
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./build:/static
    depends_on:
      - landing

  proxy:
    image: nginx:1.11
    ports:
      - "80:80"
    volumes_from:
      - landing
    depends_on:
      - landing
